# Generated by Django 4.2.3 on 2023-07-27 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bloodtype',
            table='blood_type',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patients',
        ),
    ]
