# Generated by Django 4.2.3 on 2023-07-27 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_gender_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gender',
            table='Gender',
        ),
    ]
