# Generated by Django 4.2.3 on 2023-07-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_gender_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='img',
            field=models.ImageField(blank=True, upload_to='patients'),
        ),
    ]
