# Generated by Django 4.2.3 on 2023-08-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='history',
            table='history',
        ),
    ]
