# Generated by Django 4.2.3 on 2023-07-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detections',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='detection/'),
        ),
    ]
