# Generated by Django 4.2.3 on 2023-07-30 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_gender_table'),
        ('detection', '0003_detections_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detections',
            name='user',
        ),
        migrations.AddField(
            model_name='detections',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
