# Generated by Django 4.2.3 on 2023-07-30 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_gender_table'),
        ('detection', '0004_remove_detections_user_detections_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detections',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
