# Generated by Django 4.2.3 on 2023-08-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0007_rename_cnv_detectionspredictions_cnv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'diseases',
            },
        ),
    ]
