# Generated by Django 4.2.3 on 2023-08-30 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0008_diseases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionspredictions',
            name='cnv',
        ),
        migrations.RemoveField(
            model_name='detectionspredictions',
            name='dme',
        ),
        migrations.RemoveField(
            model_name='detectionspredictions',
            name='drusen',
        ),
        migrations.AddField(
            model_name='detectionspredictions',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='detection.diseases'),
        ),
    ]
