# Generated by Django 4.2.3 on 2023-08-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0009_remove_detectionspredictions_cnv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionspredictions',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='detection_prediction/'),
        ),
    ]
