# Generated by Django 4.2.3 on 2023-08-31 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0013_detectionspredictions_prediction_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseasesCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'diseases_characteristics',
            },
        ),
        migrations.RemoveField(
            model_name='detectionspredictions',
            name='prediction_description',
        ),
        migrations.CreateModel(
            name='DetectionsPredictionsDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('detections_predictions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='detection.detectionspredictions')),
            ],
        ),
    ]
