# Generated by Django 4.2.3 on 2023-08-31 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0014_diseasescharacteristics_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detectionspredictionsdescription',
            table='detections_predictions_description',
        ),
    ]
