# Generated by Django 4.2.3 on 2023-11-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0015_alter_detectionspredictionsdescription_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiseasesCharacteristics',
        ),
        migrations.RenameField(
            model_name='detectionspredictionsdescription',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='diseases',
            old_name='nombre',
            new_name='name',
        ),
        migrations.AddField(
            model_name='diseases',
            name='abbreviation',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
