# Generated by Django 4.2.3 on 2023-11-16 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0016_delete_diseasescharacteristics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseases',
            name='abbreviation',
        ),
    ]
