# Generated by Django 4.2.3 on 2023-11-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0017_remove_diseases_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseases',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diseases',
            name='references',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
