# Generated by Django 4.2.3 on 2023-11-17 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0018_diseases_description_diseases_references'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseases',
            old_name='references',
            new_name='reference',
        ),
    ]
