# Generated by Django 4.2.3 on 2023-11-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0019_rename_references_diseases_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='description',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
